services:
  postgres:
    image: postgres:15-alpine
    container_name: moe_dobro_db
    restart: always
    environment:
      POSTGRES_DB: moe_dobro
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      # Используем 5433 вместо 5432 чтобы не конфликтовать с локальным PostgreSQL
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d moe_dobro"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
